# -*- coding: utf-8 -*-
"""necesito hacer un programa de algoritmo donde pue...

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h_FAjm_YD6WkRYVSYx02S5FOK3kZ0NSj

¡Claro! Vamos a crear un programa de algoritmo que permita calcular el área y el perímetro de diferentes figuras geométricas. Para que sea interactivo, lo haremos con un menú de opciones.

Podemos representar este algoritmo en pseudocódigo o en un lenguaje de programación real como Python, que es bastante legible. Empecemos con el pseudocódigo y luego te daré una versión en Python.

---

### **Algoritmo en Pseudocódigo**

Este pseudocódigo describe la lógica paso a paso.

```pseudocode
ALGORITMO CalcularAreaPerimetroFiguras

  INICIO

    // Bucle principal para que el usuario pueda hacer múltiples cálculos
    REPETIR HASTA que Opcion sea "0"

      MOSTRAR "------------------------------------------"
      MOSTRAR "CALCULADORA DE ÁREA Y PERÍMETRO DE FIGURAS"
      MOSTRAR "------------------------------------------"
      MOSTRAR "1. Círculo"
      MOSTRAR "2. Cuadrado"
      MOSTRAR "3. Rectángulo"
      MOSTRAR "4. Triángulo"
      MOSTRAR "5. Rombo"
      MOSTRAR "0. Salir"
      MOSTRAR "------------------------------------------"
      PEDIR "Ingrese el número de la figura que desea calcular o '0' para salir: " GUARDAR Opcion

      SEGUN Opcion HACER
        CASO "1": // Círculo
          MOSTRAR "--- CÁLCULO DE CÍRCULO ---"
          PEDIR "Ingrese el radio del círculo: " GUARDAR Radio
          SI Radio <= 0 ENTONCES
            MOSTRAR "El radio debe ser un número positivo."
          SINO
            AreaCirculo = PI * Radio * Radio
            PerimetroCirculo = 2 * PI * Radio
            MOSTRAR "El área del círculo es: " + AreaCirculo
            MOSTRAR "El perímetro (circunferencia) del círculo es: " + PerimetroCirculo
          FIN SI
        FIN CASO

        CASO "2": // Cuadrado
          MOSTRAR "--- CÁLCULO DE CUADRADO ---"
          PEDIR "Ingrese la longitud de un lado del cuadrado: " GUARDAR Lado
          SI Lado <= 0 ENTONCES
            MOSTRAR "El lado debe ser un número positivo."
          SINO
            AreaCuadrado = Lado * Lado
            PerimetroCuadrado = 4 * Lado
            MOSTRAR "El área del cuadrado es: " + AreaCuadrado
            MOSTRAR "El perímetro del cuadrado es: " + PerimetroCuadrado
          FIN SI
        FIN CASO

        CASO "3": // Rectángulo
          MOSTRAR "--- CÁLCULO DE RECTÁNGULO ---"
          PEDIR "Ingrese la longitud de la base del rectángulo: " GUARDAR BaseRectangulo
          PEDIR "Ingrese la altura del rectángulo: " GUARDAR AlturaRectangulo
          SI BaseRectangulo <= 0 O AlturaRectangulo <= 0 ENTONCES
            MOSTRAR "La base y la altura deben ser números positivos."
          SINO
            AreaRectangulo = BaseRectangulo * AlturaRectangulo
            PerimetroRectangulo = 2 * (BaseRectangulo + AlturaRectangulo)
            MOSTRAR "El área del rectángulo es: " + AreaRectangulo
            MOSTRAR "El perímetro del rectángulo es: " + PerimetroRectangulo
          FIN SI
        FIN CASO

        CASO "4": // Triángulo
          MOSTRAR "--- CÁLCULO DE TRIÁNGULO ---"
          PEDIR "Ingrese la base del triángulo: " GUARDAR BaseTriangulo
          PEDIR "Ingrese la altura del triángulo: " GUARDAR AlturaTriangulo
          PEDIR "Ingrese el lado 1 del triángulo (para perímetro): " GUARDAR Lado1Triangulo
          PEDIR "Ingrese el lado 2 del triángulo (para perímetro): " GUARDAR Lado2Triangulo
          PEDIR "Ingrese el lado 3 del triángulo (para perímetro): " GUARDAR Lado3Triangulo
          SI BaseTriangulo <= 0 O AlturaTriangulo <= 0 O Lado1Triangulo <= 0 O Lado2Triangulo <= 0 O Lado3Triangulo <= 0 ENTONCES
            MOSTRAR "Todos los valores deben ser números positivos."
          SINO
            AreaTriangulo = (BaseTriangulo * AlturaTriangulo) / 2
            PerimetroTriangulo = Lado1Triangulo + Lado2Triangulo + Lado3Triangulo
            MOSTRAR "El área del triángulo es: " + AreaTriangulo
            MOSTRAR "El perímetro del triángulo es: " + PerimetroTriangulo
          FIN SI
        FIN CASO

        CASO "5": // Rombo
          MOSTRAR "--- CÁLCULO DE ROMBO ---"
          PEDIR "Ingrese la longitud de la diagonal mayor (D): " GUARDAR DiagonalMayor
          PEDIR "Ingrese la longitud de la diagonal menor (d): " GUARDAR DiagonalMenor
          PEDIR "Ingrese la longitud de un lado del rombo (para perímetro): " GUARDAR LadoRombo // Asumimos un rombo equilátero para el perímetro
          SI DiagonalMayor <= 0 O DiagonalMenor <= 0 O LadoRombo <= 0 ENTONCES
            MOSTRAR "Todos los valores deben ser números positivos."
          SINO
            AreaRombo = (DiagonalMayor * DiagonalMenor) / 2
            PerimetroRombo = 4 * LadoRombo
            MOSTRAR "El área del rombo es: " + AreaRombo
            MOSTRAR "El perímetro del rombo es: " + PerimetroRombo
          FIN SI
        FIN CASO

        CASO "0":
          MOSTRAR "Saliendo del programa. ¡Hasta luego!"
        FIN CASO

        DEFECTO:
          MOSTRAR "Opción no válida. Por favor, intente de nuevo."
        FIN CASO

      FIN SEGUN

      MOSTRAR "" // Espacio para mejor lectura

    FIN REPETIR

  FIN
```

---

### **Implementación en Python**

Aquí tienes el mismo algoritmo implementado en Python. Python es excelente para este tipo de tareas debido a su sintaxis clara y concisa.
"""

import math

def calcular_area_perimetro_figuras():
    """
    Función principal para calcular el área y perímetro de diferentes figuras.
    """
    while True:
        print("\n------------------------------------------")
        print("CALCULADORA DE ÁREA Y PERÍMETRO DE FIGURAS")
        print("------------------------------------------")
        print("1. Círculo")
        print("2. Cuadrado")
        print("3. Rectángulo")
        print("4. Triángulo")
        print("5. Rombo")
        print("0. Salir")
        print("------------------------------------------")

        opcion = input("Ingrese el número de la figura que desea calcular o '0' para salir: ")

        if opcion == '1':
            print("\n--- CÁLCULO DE CÍRCULO ---")
            try:
                radio = float(input("Ingrese el radio del círculo: "))
                if radio <= 0:
                    print("Error: El radio debe ser un número positivo.")
                else:
                    area = math.pi * (radio ** 2)
                    perimetro = 2 * math.pi * radio
                    print(f"El área del círculo es: {area:.2f}")
                    print(f"El perímetro (circunferencia) del círculo es: {perimetro:.2f}")
            except ValueError:
                print("Error: Ingrese un número válido para el radio.")

        elif opcion == '2':
            print("\n--- CÁLCULO DE CUADRADO ---")
            try:
                lado = float(input("Ingrese la longitud de un lado del cuadrado: "))
                if lado <= 0:
                    print("Error: El lado debe ser un número positivo.")
                else:
                    area = lado ** 2
                    perimetro = 4 * lado
                    print(f"El área del cuadrado es: {area:.2f}")
                    print(f"El perímetro del cuadrado es: {perimetro:.2f}")
            except ValueError:
                print("Error: Ingrese un número válido para el lado.")

        elif opcion == '3':
            print("\n--- CÁLCULO DE RECTÁNGULO ---")
            try:
                base = float(input("Ingrese la longitud de la base del rectángulo: "))
                altura = float(input("Ingrese la altura del rectángulo: "))
                if base <= 0 or altura <= 0:
                    print("Error: La base y la altura deben ser números positivos.")
                else:
                    area = base * altura
                    perimetro = 2 * (base + altura)
                    print(f"El área del rectángulo es: {area:.2f}")
                    print(f"El perímetro del rectángulo es: {perimetro:.2f}")
            except ValueError:
                print("Error: Ingrese números válidos para la base y la altura.")

        elif opcion == '4':
            print("\n--- CÁLCULO DE TRIÁNGULO ---")
            try:
                base_tri = float(input("Ingrese la base del triángulo: "))
                altura_tri = float(input("Ingrese la altura del triángulo (para el área): "))
                lado1_tri = float(input("Ingrese el lado 1 del triángulo (para el perímetro): "))
                lado2_tri = float(input("Ingrese el lado 2 del triángulo (para el perímetro): "))
                lado3_tri = float(input("Ingrese el lado 3 del triángulo (para el perímetro): "))

                if base_tri <= 0 or altura_tri <= 0 or lado1_tri <= 0 or lado2_tri <= 0 or lado3_tri <= 0:
                    print("Error: Todos los valores deben ser números positivos.")
                else:
                    area = (base_tri * altura_tri) / 2
                    perimetro = lado1_tri + lado2_tri + lado3_tri
                    print(f"El área del triángulo es: {area:.2f}")
                    print(f"El perímetro del triángulo es: {perimetro:.2f}")
            except ValueError:
                print("Error: Ingrese números válidos para las dimensiones del triángulo.")

        elif opcion == '5':
            print("\n--- CÁLCULO DE ROMBO ---")
            try:
                diagonal_mayor = float(input("Ingrese la longitud de la diagonal mayor (D): "))
                diagonal_menor = float(input("Ingrese la longitud de la diagonal menor (d): "))
                lado_rombo = float(input("Ingrese la longitud de un lado del rombo (para perímetro): ")) # Asumimos rombo equilátero
                if diagonal_mayor <= 0 or diagonal_menor <= 0 or lado_rombo <= 0:
                    print("Error: Todos los valores deben ser números positivos.")
                else:
                    area = (diagonal_mayor * diagonal_menor) / 2
                    perimetro = 4 * lado_rombo
                    print(f"El área del rombo es: {area:.2f}")
                    print(f"El perímetro del rombo es: {perimetro:.2f}")
            except ValueError:
                print("Error: Ingrese números válidos para las dimensiones del rombo.")

        elif opcion == '0':
            print("Saliendo del programa. ¡Hasta luego!")
            break
        else:
            print("Opción no válida. Por favor, intente de nuevo.")

# Llama a la función para iniciar el programa
if __name__ == "__main__":
    calcular_area_perimetro_figuras()

"""---

### **Explicación del Código Python:**

1.  **`import math`**: Importa el módulo `math` para poder usar `math.pi` para cálculos con círculos.
2.  **`calcular_area_perimetro_figuras()`**: Esta es la función principal que contiene toda la lógica del programa.
3.  **`while True:`**: Crea un bucle infinito que se ejecutará hasta que el usuario decida salir.
4.  **Menú de Opciones**: Se imprimen las opciones disponibles para el usuario.
5.  **`input()`**: Se utiliza para pedir al usuario que ingrese su elección.
6.  **`if/elif/else`**: Se utilizan para manejar las diferentes opciones seleccionadas por el usuario.
7.  **`float(input(...))`**: Convierte la entrada del usuario (que es una cadena de texto) a un número decimal (`float`), ya que las dimensiones pueden no ser números enteros.
8.  **`try-except ValueError`**: Esto es un manejo de errores. Si el usuario ingresa algo que no es un número (por ejemplo, texto), el programa no se detendrá bruscamente, sino que mostrará un mensaje de error amigable.
9.  **Validación de entrada**: Se verifica que las dimensiones ingresadas sean positivas (`if radio <= 0:` etc.). Esto evita cálculos con valores inválidos.
10. **Fórmulas**: Dentro de cada bloque `if/elif`, se aplican las fórmulas matemáticas correspondientes para calcular el área y el perímetro.
    * **Círculo**: $Area = \pi \cdot r^2$, $Perímetro = 2 \cdot \pi \cdot r$
    * **Cuadrado**: $Area = lado^2$, $Perímetro = 4 \cdot lado$
    * **Rectángulo**: $Area = base \cdot altura$, $Perímetro = 2 \cdot (base + altura)$
    * **Triángulo**: $Area = (base \cdot altura) / 2$, $Perímetro = lado1 + lado2 + lado3$
    * **Rombo**: $Area = (D \cdot d) / 2$, $Perímetro = 4 \cdot lado$ (asumiendo un rombo equilátero donde los 4 lados son iguales).
11. **`f"El área del círculo es: {area:.2f}"`**: Esto es una "f-string" en Python, que permite formatear cadenas de texto fácilmente. El `: .2f` se utiliza para redondear el resultado a dos decimales, lo que hace la salida más legible.
12. **`break`**: Si el usuario elige '0', el bucle `while True` se detiene y el programa termina.
13. **`if __name__ == "__main__":`**: Esta es una convención común en Python. Asegura que la función `calcular_area_perimetro_figuras()` solo se llame cuando el script se ejecuta directamente (no cuando se importa como un módulo en otro script).

---

Para ejecutar el código Python:

1.  Guarda el código en un archivo con extensión `.py` (por ejemplo, `calculadora_areas.py`).
2.  Abre una terminal o línea de comandos.
3.  Navega hasta el directorio donde guardaste el archivo.
4.  Ejecuta el programa con el comando: `python calculadora_areas.py`

¡Espero que este algoritmo y su implementación te sean de gran ayuda!

<div class="md-recitation">
  Sources
  <ol>
  <li><a href="https://github.com/amaro392/tareas-python">https://github.com/amaro392/tareas-python</a></li>
  <li><a href="https://github.com/cirianodev/Python">https://github.com/cirianodev/Python</a></li>
  </ol>
</div>
"""